# 10.15 is needed for std::filesystem::exists
c_stdlib_version:           # [osx and x86_64]
  - '10.15'                 # [osx and x86_64]
# Needed for compatibility with OpenCV???
MACOSX_SDK_VERSION:         # [osx and x86_64]
  - '12.3'                  # [osx and x86_64]
