{% set version = '1.6.0' %}

package:
  name: imgui-bundle
  version: {{ version }}

source:
  # url: https://github.com/pthom/imgui_bundle/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: ffae861ff9fd47c95cc56807f028d5fe78a700f92a2a43c43f31ea2358542a68
  git_url: https://github.com/pthom/imgui_bundle.git
  git_tag: v{{ version }}
  patches:
    - 0001-Do-not-force-GLFW-to-be-recompiled.patch
    - 0002-Do-not-force-static-freetype.patch
    # https://github.com/pthom/imgui_bundle/pull/284
    - 0003-Do-not-force-linking-to-non-existent-nlohmann_json-s.patch
    - 0005-Find-glfw-correctly-for-conda-forge.patch
    - 0006-Enable-shared-libraries-for-conda-forge.patch
    - 0007-Remove-optional-dependencies-to-slim-package.patch
    - 0008-Adjust-compilation-of-immapp.patch
    - single_patch.patch
    # Adapted from
    # https://github.com/pthom/immvision/commit/733334da4ab43d9efd54ef1df0344cce39fc4625
    - drop_float16.patch

build:
  number: 1
  # hmaarrfk -- Version 1.5.2 -- Nov 30, 2024
  # windows runs out of memory on our CIs....
  # One would think that nanobind would help reduce the memory requirements of pybind
  # https://github.com/pthom/imgui_bundle/pull/266
  # But...
  # https://github.com/pthom/imgui_bundle/pull/266#issuecomment-2489688337
  # https://github.com/wjakob/nanobind/discussions/791
  # lets revisit when we have a feedstock by adding a pagefile:
  # https://github.com/conda-forge/onnxruntime-feedstock/blob/main/conda-forge.yml#L9
  # skip: true  # [win]
  skip: true  # [py<310]
  entry_points:
    - demo_imgui_bundle = imgui_bundle.demos_python.demo_imgui_bundle:main
    - imgui_bundle_demo = imgui_bundle.demos_python.demo_imgui_bundle:main
  script:
    - rm -rf external/glfw/          # [unix]
    - del /s /q external\glfw\       # [win]
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}   # [unix]
    - set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%       # [win]
    - {{ PYTHON }} -m pip install . -vvv   # [not linux]
    # Not sure why I need to specify -lGL so hard here....
    # It seems related to nanobind
    # ${external_dir}/imgui/bindings/pybind_imgui_backends.cpp
    - CFLAGS="${CFLAGS} -lGL" {{ PYTHON }} -m pip install . -vvv   # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    # - glad2-cmake
    - ninja
    # Helps find plutovg, and plutosvg
    - pkg-config
    # CMake will complain if it can't find make
    - make                                   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
  host:
    - python
    - pip
    # - glad2
    # - glad2-cmake
    - nanobind
    - scikit-build-core
    - glfw
    - freetype
    # Avoid downloading Qt (a dependency of opencv) for the CI
    # But it doesn't exist for Windows (yet)
    - libopencv *=headless*   # [not win]
    - libopencv
    - nlohmann_json
    - libgl-devel                        # [linux]
    - libglx-devel                       # [linux]
    # - libegl-devel                       # [linux]
    - plutovg
    - plutosvg
    # https://github.com/memononen/nanovg
    # nanovg is built using a lua build system that we don't have
    # premake4 is not available in conda-forge
    # - nanovg
  run:
    - python
    - typing_extensions
    - numpy
    - pydantic

    # ----------------- Optional dependencies -----------------
    # Only needed for a demo, not worth having as a hard dependency
    # - munch
    # I'm pretty sure they are only using this to get glfw installed from pypi
    # - pyopengl
    # - pyglfw
    # Seems like it is needed in a demo an in immapp_notebook.py
    # These two seem pretty auxiliary to actual usage so I'm going to
    # omit the dependency
    # - pillow

test:
  imports:
    - imgui_bundle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pthom/imgui_bundle
  summary: 'An extensive set of ready-to-use widgets and libraries, based on ImGui. Start your first app in 5 lines of code, or less.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
