{% set version = '1.6.2' %}

package:
  name: imgui-bundle
  version: {{ version }}

source:
  url: https://github.com/pthom/imgui_bundle/releases/download/v{{ version }}/srcs-full-v{{ version }}.tar.gz
  sha256: 74d7984f59d9349685dfab4190609af9fab956635522211280cf087f4f2be85f
  patches:
    - 0001-Use-conda-forge-s-plutovg.patch
    - 0002-Find-glfw-correctly-for-conda-forge.patch
    - 0003-Remove-demo-depenedencies-to-slim-down-the-package.patch

build:
  number: 2
  skip: true  # [py<310]
  entry_points:
    - demo_imgui_bundle = imgui_bundle.demos_python.demo_imgui_bundle:main
    - imgui_bundle_demo = imgui_bundle.demos_python.demo_imgui_bundle:main
  ignore_run_exports_from:
    - zlib
  script:
    - rm -rf external/glfw/          # [unix]
    - del /s /q external\glfw\       # [win]
    - export CMAKE_BUILD_PARALLEL_LEVEL=${CPU_COUNT}   # [unix]
    - set CMAKE_BUILD_PARALLEL_LEVEL=%CPU_COUNT%       # [win]
    - {{ PYTHON }} -m pip install . -vvv   # [not linux]
    # Not sure why I need to specify -lGL so hard here....
    # It seems related to nanobind
    # ${external_dir}/imgui/bindings/pybind_imgui_backends.cpp
    - CFLAGS="${CFLAGS} -lGL" {{ PYTHON }} -m pip install . -vvv   # [linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cmake
    # - glad2-cmake
    - ninja
    # Helps find plutovg, and plutosvg
    - pkg-config
    # CMake will complain if it can't find make
    - make                                   # [unix]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
  host:
    - python
    - pip
    # - glad2
    # - glad2-cmake
    - nanobind
    - scikit-build-core
    - glfw
    - freetype
    # Required to find plutosvg
    - zlib
    # Avoid downloading Qt (a dependency of opencv) for the CI
    # But it doesn't exist for Windows (yet)
    - libopencv *=headless*   # [not win]
    - libopencv
    - nlohmann_json
    - libgl-devel                        # [linux]
    - libglx-devel                       # [linux]
    # - libegl-devel                       # [linux]
    - plutovg
    - plutosvg
    # https://github.com/memononen/nanovg
    # nanovg is built using a lua build system that we don't have
    # premake4 is not available in conda-forge
    # - nanovg
  run:
    - python
    - typing_extensions
    - numpy
    - pydantic

    # ----------------- Optional dependencies -----------------
    # Only needed for a demo, not worth having as a hard dependency
    # - munch
    # I'm pretty sure they are only using this to get glfw installed from pypi
    # - pyopengl
    # - pyglfw
    # Seems like it is needed in a demo an in immapp_notebook.py
    # These two seem pretty auxiliary to actual usage so I'm going to
    # omit the dependency
    # - pillow

test:
  imports:
    - imgui_bundle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pthom/imgui_bundle
  summary: 'An extensive set of ready-to-use widgets and libraries, based on ImGui. Start your first app in 5 lines of code, or less.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
